### ISSUE TITLE
Просьба добавить класс

### ISSUE THREAD

**Issue by kturichev** [agat/css-framework#5]
Просьба добавить класс для ссылок с пунктирным подчеркиванием и переделать дизайн "стрелочки вниз" в раскрывающемся списке. 
Пользуясь случаем:
Огромное спасибо автору. Ваш проект просто находка! Давно искал такой!

**Comment by agat** [comment]
Класс для ссылок с пунктирным подчеркиванием делается одной строчкой:

``` css
a { text-decoration: none; border-bottom: 1px dashed blue; }
```

Что касается раскрывающихся списков, нужно использовать JS, вот обзор решений - http://habrahabr.ru/company/aiken/blog/114927/
